[package]
name = "imgui_support"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.36.0"

imgui = "0.12.0"
imgui-winit-support = { path = "imgui-winit-support", version = "0.13.0" }
imgui-glium-renderer = { path = "imgui-glium-renderer", version = "0.13.0" }