name: ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rustfmt:
    name: Check rustfmt
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: cargo fmt --all -- --check

  test:
    name: Lint and test
    # this is pretty weird, but `winit` requires a backend on linux
    # and we don't specify that at all and just let end users do that
    runs-on: windows-latest
    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: clippy
        run: cargo clippy

      - name: test
        run: cargo test
